sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image"
  - docker build -t jk121926/docker-react-app -f Dockerfile.dev

script:
  - docker run -e CI=true jk121926/docker-react-app npm run test --  --coverage

after_success:
  - echo "Test success"